services:
  app:
    build: .
    image: ms-consultas
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
      - '27018:27018'
      - '27019:27019'