apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
  name: ms-consultas
spec:
  selector:
    app: ms-consultas
  type: NodePort
  ports:
  - port: 3000
    targetPort: 8080
    nodePort: 30003
