apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-consultas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-consultas
  template:
    metadata:
      labels:
        app: ms-consultas
    spec:
      serviceAccountName: irsasecrets
      containers:
        - name: ms-consultas
          image: 851725345801.dkr.ecr.us-east-1.amazonaws.com/ms-consultas:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: JWT_SECRET
              value: "secret1234"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: documentdb-secret-consultas
                  key: urlConsultas
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets-ms-consultas"  # Nome do seu SecretProviderClass
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-consultas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-consultas
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
