apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-ms-consultas
spec:
  provider: aws
  secretObjects:
  - data:
    - key: urlConsultas
      objectName: documentdbcredentials
    secretName: documentdb-secret-consultas
    type: Opaque
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:851725345801:secret:documentdbcredentials-gxwTek"
          objectType: "secretsmanager"
          jmesPath:
            - path: urlConsultas
              objectAlias: urlConsultas
